os: osx
osx_image: xcode11.4
language:
    - swift
install:
    - gem install cocoapods --pre
    - cd Convoy
    - pod install --repo-update
script:
  - xcodebuild -scheme Travis -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' build
