os: osx
osx_image: xcode11.4
language:
    - swift
install:
    - >
      cd Convoy
      pod install
script:
  - xcodebuild -scheme Travis -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build
