os: osx
osx_image: xcode11.4
language:
    - swift
before_install:
  - gem install cocoapods --pre
install:
    - >
      cd Convoy
      pod install --repo-update
script:
  - xcodebuild -scheme Travis -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build
