os: osx
git:
    submodules: false
osx_image: xcode11.4
language:
    - swift
cache:
    cocoapods: true
    directories:
        - $HOME/.cache/firebase
podfile: Convoy/Podfile
install:
    - brew install node
    - npm install -g firebase-tools
    - gem install xcpretty
    - gem install cocoapods --pre
    - cd Convoy
    - pod install --repo-update
before_script:
    - cd ../firebaseCloudFuncs


script:
    - firebase emulators:exec --project convoy-da5eb --only firestore,functions --token 1//032fpn7nF_emXCgYIARAAGAMSNwF-L9IrHr66L3QwdPqlpkymXJ9dn5e3Q7EXlMgJY12mTAhbe3oXJ2SSyEVU46-aXFWAk9xNN3E './unitTests.sh'
    
