# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Convoy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Convoy
  pod 'MapboxNavigation', '~> 0.39.0'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseUI', '~> 8.4.2'


end
